name: to_do_app
description: Yandex Academy test app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logging: ^1.0.2

  

  url_launcher: ^6.1.4


dev_dependencies:
  linter: ^1.26.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
