name: to_do_app
description: Yandex Academy test app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logging: ^1.0.2

  uuid: ^3.0.6

  freezed: ^2.1.0+1

  build_runner: ^2.2.0

  freezed_annotation: ^2.1.0

  dio: ^4.0.6

  json_annotation: ^4.6.0

  flutter_slidable: ^2.0.0

  flutter_bloc: ^8.1.1

  hive_flutter: ^1.1.0

  hive_generator: ^1.1.3

  connectivity_plus: ^2.3.6+1

  url_launcher: ^6.1.4

  date_format: ^2.0.5

  shared_preferences: ^2.0.15

  appmetrica_plugin: ^1.0.1

  bloc_test: ^9.1.0



dev_dependencies:
  linter: ^1.26.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  mockito: ^5.3.0
  json_serializable: ^6.3.1


  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
